# Site settings
title: Predictors of Permanent Housing for Homeless Families
email: arokem@gmail.com
description: ""
url: "https://uwescience.github.io"
baseurl: "/DSSG2015-predicting-permanent-housing"
permalink: "/:title/"
twitter_username: uwescience
github_username:  uwescience

# Build settings
markdown: kramdown
